#!/bin/sh

# Arguments - upstream kde tarballs

PREFIX="kdeapi"

get_orig_name() {
    local tarball upstream
    local name version

    tarball="$1"
    upstream=`basename "$tarball" ".tar.bz2"`
    name=${upstream%%-*}
    version=${upstream#*-}

    echo "${PREFIX}_${version}.orig-${name}.tar.bz2 $name"
}

create_empty_tarball() {
    local dummy tarball
    tarball="${1%.bz2}"
    dummy=`mktemp dummy.XXXXXX`
    tar cf "${tarball}" $dummy
    tar --delete --file "${tarball}" $dummy
    bzip2 "$tarball"
    rm -f $dummy
}

orig=""
while [ -n "$1" ]; do
    echo "Renaming and extracting tarball $1 ..." >&1
    orig="../`get_orig_name "$1"`"
    name=${orig#* }
    orig=${orig% *}
    rm -f "$orig"
    ln -f "$1" "$orig"
    rm -rf "$name"
    mkdir "$name"
    tar xjf "$orig" --strip=1 -C "$name"
    shift
done

orig="${orig%.orig-*.tar.bz2}.orig.tar.bz2"
echo "Creating empty $orig ..." >&1
rm -f "$orig"
create_empty_tarball "$orig"
